jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace hierarchical_variational_inference.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace real_nvp.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace mmd_vae.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace normalizing_flow_toy.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace real_nvp_cond.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace glow.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace maximum_likelihood.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace jmvae_poe.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace vae.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace jmvae.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace distributions.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace vae_with_vae_class.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace real_nvp_toy.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace real_nvp_cifar.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace vi.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace gan.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace cvae.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace gmm.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace m2.ipynb
jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=pixyz_py38 --execute --inplace mvae.ipynb
